### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by teamjojo** [matteyeux/autodecrypt#1]
Hello i am trying to decrypt a img3 file and get the following error

python3 autodecrypt -f /Users/joranosinga/Downloads/iPad2\,5_9.3.5_13G36_Restore/Firmware/all_flash/all_flash.p105ap.production/iBoot.p105.RELEASE.img3 -i 9.3.5 -d iPad2,5
Traceback (most recent call last):
  File "autodecrypt", line 130, in <module>
    magic, image_type = decrypt_img.get_image_type(file)
  File "./decrypt_img.py", line 13, in get_image_type
    with open(filename, 'rb') as file:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by matteyeux** [comment]
Hi,
If you want to decrypt an already downloaded file use `-l` flag like this :  `python3 autodecrypt -f /path/to/iBoot -i 9.3.5 -d iPad2,5 -l`

The default behavior of autodecrypt is to use remotezip to **only** download the IMG3 to decrypt.
