### ISSUE TITLE
 foreman api keys down

### ISSUE THREAD

**Issue by P5-2005** [matteyeux/autodecrypt#14]
<details>
C:\Users\BH11040\Downloads\autodecrypt-master>autodecrypt -f iBSS -i 10.3.3 -d iPhone6,2
[w] could not get OTA url, trying with IPSW url
[i] downloading iBSS.iphone6.RELEASE.im4p
[i] image : ibss
[i] grabbing keys for iPhone6,2/14G60
[x] iv  : f2aa35f6e27c409fd57e9b711f416cfe
[x] key : 599d9b18bc51d93f2385fa4e83539a2eec955fce5f4ae960b252583fcbebfe75
[i] decrypting iBSS.iphone6.RELEASE.im4p to iBSS.iphone6.RELEASE.bin...
[x] done
</details>

when adding foreman api keys i got this :

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='foreman-public.sudosecuritygroup.com', port=443): Max retries exceeded with url: /api/find/combo/iPhone6,2/16H62 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025001554790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by matteyeux** [comment]
I am not the owner of foreman. I can't do much

**Comment by P5-2005** [comment]
i mention this to remove it from readme thats all not to make it up again xD

**Comment by matteyeux** [comment]
I mean, this instance is down, but you can still make your own, as the code is open source : https://github.com/GuardianFirewall/foreman.

That's why I keep this example in the README for the moment.
