### ISSUE TITLE
How to use this tool to decrypt keys from device with Iphone8,2 after checkra1n jailbreak on ios 13.6

### ISSUE THREAD

**Issue by TherealXmeD** [matteyeux/autodecrypt#4]
Hello.

I have tried to get the keys from my device using autodecrypt. I have installed all the dependencies ( I hope). when I use the command that is in the readme on this GitHub under the section decrypt keys from device. I cant seem to get anything to work all I get is the iBoot file. The rest is errors:

 autodecrypt -f iBoot -i 13.6 -d iPhone8,1 --ip 192.168.1.27
[i] downloading iBoot.n71.RELEASE.im4p
[i] grabbing keys from gidaes server on %s:12345 192.168.1.27
Traceback (most recent call last):
  File "/home/xmed/.local/bin/autodecrypt", line 11, in <module>
    load_entry_point('autodecrypt==2.0.2', 'console_scripts', 'autodecrypt')()
  File "/home/xmed/.local/lib/python3.7/site-packages/autodecrypt-2.0.2-py3.7.egg/autodecrypt/autodecrypt.py", line 110, in main
  File "/home/xmed/.local/lib/python3.7/site-packages/autodecrypt-2.0.2-py3.7.egg/autodecrypt/decrypt_img.py", line 53, in get_kbag
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'img4': 'img4'

I have the img4lib and img4

Im on linux(ubuntu)

Thank you for your help. I am new to all this and I dont know if Im posting in the right place and if it is correct to post about this.
New to github and ios cfw and jailbreak.
Thanks again :)

**Comment by matteyeux** [comment]
Is `img4` binary in your $PATH ? Try to copy it to `/usr/local/lib`. 

Also, since latest checkra1n update, the kernel patches to access AES engine from userland are disabled.

**Comment by TherealXmeD** [comment]
I have done so. Same result. I will pop out the old hackintosh and see if i have an older version of checkra1n

**Comment by TherealXmeD** [comment]
Or do you know how i could enzble the patches?

**Comment by TherealXmeD** [comment]
Hello again.

I have moved the img4 bin to usr/local/lib/
Then i jailbroke my iphone 6s (8,1) with checkra1n  0.10.1 (i tried with 0.9.8 and 0.9.8.2 but the phone did not boot.)

I thn ran autodecrypt in virtualenv with python3.7 and same error.

Any ideas? Am i doing something wrong? Or could the tsssaver tweak or openssh do anything knowing does are the only tweaks i hv on this device.

Thank you for yor help.

**Comment by matteyeux** [comment]
Make sur img4 bin is on your laptop not your iPhone. Also, I am not sure which version of checkra1n disables the patch for IOAESaccelerator so 0.10.1 maybe does not work.

Tweaks installed should not cause any issue with autodecrypt (unless the port 12345 is binded by one of them)

**Comment by TherealXmeD** [comment]
Thanks for the response i will try again with a different version of checkra1n
