### ISSUE TITLE
iPad2,2

### ISSUE THREAD

**Issue by tolikes** [matteyeux/autodecrypt#5]
[i] downloading iBoot.k94.RELEASE.img3
Traceback (most recent call last):
  File "./autodecrypt.py", line 129, in <module>
    main()
  File "./autodecrypt.py", line 106, in main
    magic, image_type = decrypt_img.get_image_type(parser.img_file)
TypeError: cannot unpack non-iterable NoneType object

**Comment by matteyeux** [comment]
What are the parameters passed to the command ?

**Comment by tolikes** [comment]
fixed issue
